services:
  redis:
    image: redis:7-alpine
    container_name: miniapp-redis
    ports:
      - "6379:6379"

  api:
    build: ./backend
    container_name: miniapp-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_URL: ${REDIS_URL}
      CHUNK_SIZE: ${CHUNK_SIZE}
    volumes:
      - ./backend/app:/app/app

  worker:
    build: ./backend
    container_name: miniapp-worker
    command: celery -A app.celery_app.celery worker --loglevel=info
    depends_on:
      - redis
    environment:
      REDIS_URL: ${REDIS_URL}
      CHUNK_SIZE: ${CHUNK_SIZE}
    volumes:
      - ./backend/app:/app/app

  flower:
    build: ./backend
    container_name: miniapp-flower
    command: celery -A app.celery_app.celery flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      REDIS_URL: ${REDIS_URL}
    volumes:
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    container_name: miniapp-frontend
    ports:
      - "3002:80"
    depends_on:
      - api
